### ISSUE TITLE
ArgumentError on Vips::Image#new

### ISSUE THREAD

**Issue by felixbuenemann** [jcupitt/gir_ffi-vips#2]
I played around with gif_ffi-vips today (to see if I can use vips in jruby) and it seems to be broken:

``` ruby
image = Vips::call "black", 200, 200
ArgumentError:
 wrong number of arguments (given 0, expected 1)
# ./lib/vips8/image.rb:521:in `get_value'
# ./lib/vips8/argument.rb:135:in `get_value'
# ./lib/vips8/call.rb:161:in `block in call_base'
# ./lib/vips8/call.rb:156:in `each'
# ./lib/vips8/call.rb:156:in `call_base'
# ./lib/vips8/call.rb:257:in `call'
# ./spec/vips_spec.rb:9:in `block (3 levels) in <top (required)>'
```

I got around that issue using the following patch:

``` diff
diff --git a/lib/vips8/argument.rb b/lib/vips8/argument.rb
index baf96c3..5f576d1 100644
--- a/lib/vips8/argument.rb
+++ b/lib/vips8/argument.rb
@@ -132,7 +132,7 @@ module Vips
         end

         def get_value
-            Argument::unwrap(@op.property(@name).get_value)
+            Argument::unwrap(@op.property(@name))
         end

         def description
diff --git a/lib/vips8/image.rb b/lib/vips8/image.rb
index f504983..6ac39f3 100644
--- a/lib/vips8/image.rb
+++ b/lib/vips8/image.rb
@@ -519,11 +519,11 @@ module Vips
         #
         # Use #get to fetch a GValue directly.
         def get_value(name)
-            # get the GValue
-            value = get name
-
-            # pull out the value
-            value = value.get_value
+            ret, gval = get name
+            if ret[0] != 0
+                raise Vips::Error, "Field #{name} not found."
+            end
+            value = gval.value

             Argument::unwrap(value)
         end
```

But now it fails when trying to access the `image.width` property:

``` ruby
image = Vips::call "black", 200, 200
image.width
Vips::Error:
 VipsOperation: class "width" not found
# ./lib/vips8/call.rb:22:in `call_base'
# ./lib/vips8/image.rb:239:in `method_missing'
# ./spec/vips_spec.rb:11:in `block (3 levels) in <top (required)>'
```

In ruby-vips8 it seems this method is dynamically defined by the gobject-introspection loader. Here it isn't and so it runs into the method_missing handler.

Just run the test suite and the errors should come up.

**Comment by jcupitt** [comment]
Yes, `gir_ffi-vips` is not in a working state at the moment, mvz has been changing the way references and GC are handled to try to help vips not leak and I've not yet finished updating it to the new way.

There have been a couple of issues on gir_ffi about this if you're curious, the latest was:

https://github.com/mvz/gir_ffi/issues/54

I'd like to get `gir_ffi-vips` working, I like the idea of having no C at all in the binding, just ffi, but in the meantime the ruby-vips8 gem should work, I hope.
